# Travis CI configuration file for psycopg2

dist: trusty
sudo: required
language: python

python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
  - "pypy3.5"

install:
  - python setup.py install
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

notifications:
  email: false
